# Generated by Django 5.2 on 2025-04-10 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='po',
            old_name='email',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='po',
            name='address',
        ),
        migrations.RemoveField(
            model_name='po',
            name='city',
        ),
        migrations.RemoveField(
            model_name='po',
            name='country',
        ),
        migrations.RemoveField(
            model_name='po',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='po',
            name='order_note',
        ),
        migrations.RemoveField(
            model_name='po',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='po',
            name='state',
        ),
        migrations.RemoveField(
            model_name='po',
            name='zip_code',
        ),
    ]
