# Generated by Django 3.1.12 on 2025-04-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_email_po_password_remove_po_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
