# Generated by Django 5.2 on 2025-04-19 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_po_id_alter_po_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='po',
        ),
    ]
